project_name: mfaws

before:
  hooks:
    - go mod download

builds:
  -
    binary: '{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  -
    format: binary
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - none*

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - mfaws
    dockerfile: build/package/Dockerfile
    image_templates:
      - "pbar1/{{ .ProjectName }}:{{ .Tag }}"
      - "pbar1/{{ .ProjectName }}:{{ .Major }}"
      - "pbar1/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "pbar1/{{ .ProjectName }}:latest"
